      - name: Configure & build kernel (auto-detect defconfig)
        run: |
          set -euxo pipefail
          cd op7t_kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE="ccache aarch64-linux-gnu-"

          echo ">>> Listing available defconfigs:"
          ls -1 arch/arm64/configs | sed -n '1,200p' || true

          # Try to auto-detect the correct defconfig file
          DEFCONFIG=""
          for CAND in \
            hotdogb_defconfig \
            vendor/hotdogb_defconfig \
            hotdog_defconfig \
            vendor/hotdog_defconfig \
            oneplus7t_defconfig \
            vendor/oneplus7t_defconfig \
            oneplus_defconfig \
            vendor/oneplus_defconfig \
            sm8150_defconfig \
            vendor/sm8150_defconfig
          do
            if [ -f "arch/arm64/configs/$CAND" ]; then
              DEFCONFIG="$CAND"
              break
            fi
          done

          if [ -z "$DEFCONFIG" ]; then
            echo "Could not find a matching defconfig in arch/arm64/configs/"
            echo "Dumping a grep of likely candidates:"
            grep -RIl --include="*defconfig" -E 'hotdog|oneplus|sm8150' arch/arm64/configs || true
            exit 1
          fi

          echo ">>> Using defconfig: $DEFCONFIG"
          make O=out "$DEFCONFIG"
          make -j"$(nproc)" O=out
          ccache -s || true
